---
- name: Deploy app to Kubernetes
  hosts: local
  tasks:
    - name: Apply MongoDB Deployment
      kubernetes.core.k8s:
        state: present
        src: ../k8s/mongo-deployment.yml

    - name: Apply Backend Deployment with dynamic image
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: backend
            namespace: default
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: backend
            template:
              metadata:
                labels:
                  app: backend
              spec:
                containers:
                  - name: backend
                    image: "{{ backend_image | default('christopherian2004/devops-backend:latest') }}"
                    imagePullPolicy: IfNotPresent
                    ports:
                      - containerPort: 3000
                    env:
                      - name: MONGO_URL
                        value: mongodb://mongo:27017/devopsdb
